# CREATE NEW FILE: api_ops.py
# Route specs for ops/diagnostics endpoints.
# This file contains only route metadata (no runtime imports from dashboard_server.py).

ROUTE_SPECS = [
    ("GET", "/api/alerts", "api_get_alerts"),
    ("GET", "/api/validation", "api_get_validation"),
    ("GET", "/api/model/diagnostics", "api_get_model_diagnostics"),
    ("GET", "/api/model/registry", "api_get_model_registry"),
    ("GET", "/api/embed_model_eval", "api_get_embed_model_eval"),
    ("GET", "/api/embed_conf_calib", "api_get_embed_conf_calib"),
    ("GET", "/api/temporal/eval", "api_get_temporal_eval"),
    ("GET", "/api/temporal/models", "api_get_temporal_models"),
    ("GET", "/api/portfolio/backtest/latest", "api_get_latest_portfolio_backtest"),
    ("GET", "/api/execution/metrics", "api_get_execution_metrics"),
    ("GET", "/api/execution/metrics/rolling", "api_get_execution_metrics_rolling"),
    ("GET", "/api/execution/metrics/by_symbol", "api_get_execution_metrics_by_symbol"),
    ("GET", "/api/execution/metrics/by_confidence", "api_get_execution_cost_by_confidence"),
    ("GET", "/api/social/features", "api_get_social_features"),
    ("GET", "/api/social/regimes", "api_get_social_regimes"),
    ("GET", "/api/social/blocks", "api_get_social_blocks"),
    ("GET", "/api/confidence_mass", "api_get_confidence_mass"),
    ("POST", "/api/promotion/rollback", "api_post_rollback"),
]

ROUTE_SPECS.append(("GET", "/api/ai/ops_explain", "api_get_ai_ops_explain"))

ROUTE_SPECS_OPS = ROUTE_SPECS


# ----------------------------------------------------------------------
# AI Ops Copilot (read-only advisory)
# ----------------------------------------------------------------------

import time
import json


def api_get_ai_ops_explain(_parsed, ctx):
    """Return an ops snapshot plus an AI explanation string.

    The explanation is generated by consulting an LLM via the existing
    voice/llm helper.  The prompt is strictly advisory and warns the model
    not to execute any actions or trades.
    """
    # build snapshot using health helper and job list
    try:
        from engine.runtime.health import get_ops_snapshot
    except Exception:
        get_ops_snapshot = None

    if get_ops_snapshot:
        try:
            jobs = ctx.get("JOBS").list_jobs() if ctx.get("JOBS") else []
            snap = get_ops_snapshot(jobs=jobs)
        except Exception as e:
            snap = {"error": f"snapshot_failed:{e}"}
    else:
        snap = {"error": "no_snapshot_function"}

    prompt = (
        "You are an AI operations assistant that only explains the system state."
        " Do not perform any fixes or trades.\n"
        "Here is the current system snapshot in JSON format:\n\n"
        f"{json.dumps(snap, indent=2)}\n\n"
        "Questions to answer:\n"
        "- What is broken?\n"
        "- How bad is it?\n"
        "- What happens next?\n"
        "Respond concisely in human language and make it clear you are only an adviser."
    )

    try:
        from engine.api.api_voice import _run_llm_explain_with_timeout, VOICE_TIMEOUT_S, VOICE_MAX_RESPONSE_CHARS
        explanation = _run_llm_explain_with_timeout(prompt, VOICE_TIMEOUT_S)
        if VOICE_MAX_RESPONSE_CHARS and len(explanation) > VOICE_MAX_RESPONSE_CHARS:
            explanation = explanation[:VOICE_MAX_RESPONSE_CHARS]
    except Exception as e:
        return {"ok": False, "error": str(e), "snapshot": snap}

    return {"ok": True, "snapshot": snap, "explanation": explanation}
