"""
Adaptive Alerting System

Integrates human-alignment AI with the alert system to provide dynamic
threshold adjustment and relevance-based filtering while maintaining safety.
"""

import time
import logging
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass
from enum import Enum
import json

from engine.storage import connect
from engine.runtime.alerts import (
    emit_alert, DEFAULT_RULES, choose_rule, _passes_rate_limit, 
    _passes_cooldown, _get_validation_row, _support_n, _passes_quality_gates,
    MIN_RELEVANCE, ALERT_DEDUPE_WINDOW_S
)
from engine.runtime.alert_interaction_tracker import interaction_tracker, InteractionType
from engine.runtime.human_alignment_ai import human_alignment_ai, AdaptationAction

logger = logging.getLogger(__name__)

class FilterReason(Enum):
    """Reasons for filtering out alerts"""
    LOW_RELEVANCE = "low_relevance"
    RATE_LIMIT = "rate_limit"
    COOLDOWN = "cooldown"
    QUALITY_GATE = "quality_gate"
    CRITICAL_SAFETY = "critical_safety"
    ADAPTIVE_THRESHOLD = "adaptive_threshold"

@dataclass
class AdaptiveAlertConfig:
    """Configuration for adaptive alerting"""
    enable_adaptive_thresholds: bool = True
    enable_relevance_filtering: bool = True
    min_relevance_threshold: float = 0.3
    critical_safety_margin: float = 0.1
    adaptive_factor: float = 0.2
    learning_integration: bool = True
    
class AdaptiveAlerting:
    """Main adaptive alerting system"""
    
    def __init__(self, config: Optional[AdaptiveAlertConfig] = None):
        self.config = config or AdaptiveAlertConfig()
        self.adaptation_cache: Dict[str, Dict[str, Any]] = {}
        self.last_cache_update = 0
        self.cache_ttl = 300  # 5 minutes
        
        # Statistics
        self.stats = {
            'total_alerts_evaluated': 0,
            'alerts_emitted': 0,
            'alerts_filtered': 0,
            'adaptive_adjustments_applied': 0,
            'relevance_filters_applied': 0
        }
        
        logger.info("AdaptiveAlerting initialized")
    
    def emit_adaptive_alert(self, event_title: str, symbol: str, horizon_s: int,
                          expected_z: float, confidence: float, 
                          explain: Optional[Dict] = None,
                          operator_id: Optional[str] = None) -> Optional[int]:
        """Emit alert with adaptive filtering and threshold adjustment"""
        
        self.stats['total_alerts_evaluated'] += 1
        
        # Get base rule
        base_rule = choose_rule(expected_z, confidence, symbol, horizon_s)
        if not base_rule:
            return None
        
        # Apply adaptive adjustments
        adapted_rule = self._apply_adaptive_adjustments(base_rule, symbol, horizon_s, expected_z, confidence)
        
        # Check relevance filtering
        if self.config.enable_relevance_filtering:
            relevance_score = self._get_relevance_score(adapted_rule, symbol, horizon_s)
            if relevance_score < self.config.min_relevance_threshold:
                self._filter_alert(base_rule, FilterReason.LOW_RELEVANCE, 
                                 {'relevance_score': relevance_score})
                return None
        
        # Apply quality gates and rate limits
        if not self._passes_safety_checks(symbol, horizon_s, adapted_rule['severity']):
            return None
        
        # Emit the alert with adapted parameters
        alert_id = emit_alert(
            event_title, symbol, horizon_s, expected_z, confidence, explain,
            rules=[adapted_rule]  # Use adapted rule instead of default rules
        )
        
        if alert_id:
            self.stats['alerts_emitted'] += 1
            
            # Track that this alert was generated by adaptive system
            self._track_adaptive_alert(alert_id, adapted_rule, base_rule)
            
            logger.info(f"Emitted adaptive alert {alert_id} with rule {adapted_rule['rule_id']}")
        
        return alert_id
    
    def _apply_adaptive_adjustments(self, base_rule: Dict[str, Any], symbol: str, 
                                  horizon_s: int, expected_z: float, confidence: float) -> Dict[str, Any]:
        """Apply learned adaptations to rule"""
        if not self.config.enable_adaptive_thresholds:
            return base_rule
        
        # CRITICAL SAFETY: Never reduce thresholds for critical alerts
        if base_rule['severity'] == 'CRIT':
            return base_rule
        
        # Create a copy to modify
        adapted_rule = base_rule.copy()
        
        # Get latest adaptations for this rule configuration
        adaptations = self._get_adaptations_for_rule(
            base_rule['rule_id'], base_rule['severity'], symbol, horizon_s
        )
        
        # Apply threshold adjustments with safety limits
        if 'threshold_adjustment' in adaptations:
            adjustment = adaptations['threshold_adjustment']
            
            # For HIGH severity, limit threshold increases
            if base_rule['severity'] == 'HIGH' and adjustment > 1.0:
                adjustment = min(adjustment, 1.0 + self.config.critical_safety_margin)
            
            # Never reduce thresholds below minimum safety levels
            min_threshold = self._get_minimum_safe_threshold(base_rule['severity'])
            adapted_rule['min_abs_z'] = max(min_threshold, adapted_rule['min_abs_z'] * adjustment)
            adapted_rule['rule_id'] = f"{base_rule['rule_id']}_adj"
            self.stats['adaptive_adjustments_applied'] += 1
        
        # Apply confidence adjustments (only increases for safety)
        if 'confidence_adjustment' in adaptations:
            adjustment = adaptations['confidence_adjustment']
            if adjustment > 1.0:  # Only allow confidence increases
                adapted_rule['min_conf'] = min(0.99, adapted_rule['min_conf'] * adjustment)
        
        # Apply severity adjustments (only upgrades, never downgrades)
        if 'severity_override' in adaptations:
            new_severity = adaptations['severity_override']
            # Only allow severity upgrades for safety
            if self._can_upgrade_severity(base_rule['severity'], new_severity):
                adapted_rule['severity'] = new_severity
                adapted_rule['rule_id'] = f"{base_rule['rule_id']}_sev"
        
        return adapted_rule
    
    def _get_adaptations_for_rule(self, rule_id: str, severity: str, 
                                symbol: str, horizon_s: int) -> Dict[str, Any]:
        """Get applied adaptations for a specific rule configuration"""
        # Check cache first
        cache_key = f"{rule_id}_{severity}_{symbol}_{horizon_s}"
        now = time.time()
        
        if (cache_key in self.adaptation_cache and 
            now - self.adaptation_cache[cache_key]['timestamp'] < self.cache_ttl):
            return self.adaptation_cache[cache_key]['adaptations']
        
        adaptations = {}
        
        try:
            con = connect()
            # Get most recent applied adaptations
            row = con.execute("""
                SELECT action, recommended_value, confidence
                FROM alert_adaptations 
                WHERE rule_id = ? AND severity = ? AND symbol = ? AND horizon_s = ?
                  AND status = 'applied'
                ORDER BY applied_ms DESC
                LIMIT 1
            """, (rule_id, severity, symbol, horizon_s)).fetchone()
            
            if row:
                action, value, confidence = row
                
                if action == 'increase_threshold' and confidence > 0.7:
                    adaptations['threshold_adjustment'] = 1.0 + (value - 1.0) * confidence
                elif action == 'decrease_threshold' and confidence > 0.7:
                    adaptations['threshold_adjustment'] = 1.0 - (1.0 - value) * confidence
                elif action == 'change_severity' and confidence > 0.8:
                    adaptations['severity_override'] = value
            
            # Store in cache
            self.adaptation_cache[cache_key] = {
                'adaptations': adaptations,
                'timestamp': now
            }
            
        except Exception as e:
            logger.error(f"Failed to get adaptations: {e}")
        finally:
            try:
                con.close()
            except:
                pass
        
        return adaptations
    
    def _can_upgrade_severity(self, current: str, new: str) -> bool:
        """Check if severity upgrade is allowed"""
        severity_order = {'INFO': 0, 'WARN': 1, 'HIGH': 2, 'CRIT': 3}
        return severity_order.get(new, 0) > severity_order.get(current, 0)
    
    def _get_minimum_safe_threshold(self, severity: str) -> float:
        """Get minimum safe threshold for severity level"""
        safe_thresholds = {
            'INFO': 0.5,    # Can be filtered aggressively
            'WARN': 0.8,    # Moderate safety
            'HIGH': 1.2,    # High safety, but can be adjusted
            'CRIT': 1.5     # Never reduced below this
        }
        return safe_thresholds.get(severity, 1.0)
    
    def _get_relevance_score(self, rule: Dict[str, Any], symbol: str, horizon_s: int) -> float:
        """Get relevance score for alert configuration"""
        return interaction_tracker.get_relevance_score(
            rule['rule_id'], rule['severity'], symbol, horizon_s
        )
    
    def _passes_safety_checks(self, symbol: str, horizon_s: int, severity: str) -> bool:
        """Apply safety checks before emitting alert"""
        # CRITICAL SAFETY: Never suppress critical alerts
        if severity == 'CRIT':
            # Critical alerts always pass through, only rate limit for emergency scenarios
            now_ms = int(time.time() * 1000)
            if not _passes_rate_limit(symbol, now_ms):
                logger.critical(f"CRITICAL alert rate limited for {symbol} - SYSTEM STRESS DETECTED")
                return False
            return True
        
        # Rate limiting for non-critical alerts
        now_ms = int(time.time() * 1000)
        if not _passes_rate_limit(symbol, now_ms):
            self._filter_alert(None, FilterReason.RATE_LIMIT, {'symbol': symbol})
            return False
        
        # Cooldown checks (relaxed for HIGH severity)
        if severity == 'HIGH':
            # Reduced cooldown for HIGH severity alerts
            cutoff = now_ms - (1800 * 1000)  # 30 minutes instead of default
            con = connect()
            try:
                row = con.execute(
                    """
                    SELECT severity
                    FROM alerts
                    WHERE symbol=? AND horizon_s=? AND ts_ms>=?
                    ORDER BY ts_ms DESC
                    LIMIT 1
                    """,
                    (symbol, horizon_s, cutoff),
                ).fetchone()
            finally:
                con.close()
            
            if row and row[0] == 'CRIT':
                # If there was a critical alert recently, allow this HIGH alert
                return True
        elif not _passes_cooldown(symbol, horizon_s, severity, now_ms):
            self._filter_alert(None, FilterReason.COOLDOWN, 
                             {'symbol': symbol, 'horizon_s': horizon_s, 'severity': severity})
            return False
        
        # Quality gates (never block HIGH/CRITICAL for quality issues, just warn)
        if not _passes_quality_gates(symbol, horizon_s):
            if severity in ['HIGH', 'CRIT']:
                logger.warning(f"Quality gate failed for {severity} alert {symbol}/{horizon_s} - allowing through")
                return True
            else:
                self._filter_alert(None, FilterReason.QUALITY_GATE, 
                                 {'symbol': symbol, 'horizon_s': horizon_s})
                return False
        
        return True
    
    def _filter_alert(self, rule: Optional[Dict[str, Any]], reason: FilterReason, 
                     context: Dict[str, Any]):
        """Record filtered alert for learning"""
        self.stats['alerts_filtered'] += 1
        
        if reason == FilterReason.LOW_RELEVANCE:
            self.stats['relevance_filters_applied'] += 1
        
        # Log filtering for learning
        logger.debug(f"Alert filtered: {reason.value} - {context}")
    
    def _track_adaptive_alert(self, alert_id: int, adapted_rule: Dict[str, Any], 
                            base_rule: Dict[str, Any]):
        """Track that this alert was generated by adaptive system"""
        try:
            con = connect()
            con.execute("""
                CREATE TABLE IF NOT EXISTS adaptive_alert_tracking (
                    alert_id INTEGER PRIMARY KEY,
                    base_rule_id TEXT NOT NULL,
                    adapted_rule_id TEXT NOT NULL,
                    base_threshold REAL NOT NULL,
                    adapted_threshold REAL NOT NULL,
                    base_severity TEXT NOT NULL,
                    adapted_severity TEXT NOT NULL,
                    adaptations_json TEXT,
                    created_ms INTEGER NOT NULL
                )
            """)
            
            adaptations = {
                'threshold_changed': adapted_rule['min_abs_z'] != base_rule['min_abs_z'],
                'severity_changed': adapted_rule['severity'] != base_rule['severity'],
                'confidence_changed': adapted_rule.get('min_conf') != base_rule.get('min_conf')
            }
            
            con.execute("""
                INSERT INTO adaptive_alert_tracking 
                (alert_id, base_rule_id, adapted_rule_id, base_threshold, adapted_threshold,
                 base_severity, adapted_severity, adaptations_json, created_ms)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                alert_id, base_rule['rule_id'], adapted_rule['rule_id'],
                base_rule['min_abs_z'], adapted_rule['min_abs_z'],
                base_rule['severity'], adapted_rule['severity'],
                json.dumps(adaptations), int(time.time() * 1000)
            ))
            
            con.commit()
        except Exception as e:
            logger.error(f"Failed to track adaptive alert: {e}")
        finally:
            try:
                con.close()
            except:
                pass
    
    def track_operator_interaction(self, alert_id: int, interaction_type: InteractionType,
                                 operator_id: Optional[str] = None, 
                                 context: Optional[Dict[str, Any]] = None):
        """Track operator interaction with adaptive alert"""
        success = interaction_tracker.track_interaction(
            alert_id, interaction_type, operator_id, context=context
        )
        
        if success:
            # Trigger learning cycle if enough data
            self._maybe_trigger_learning()
        
        return success
    
    def _maybe_trigger_learning(self):
        """Trigger learning cycle if conditions are met"""
        if not self.config.learning_integration:
            return
        
        # Check if we have enough recent interactions
        recent_interactions = len(interaction_tracker.interaction_history)
        if recent_interactions >= 20:  # Threshold for triggering learning
            try:
                recommendations = human_alignment_ai.learn_from_interactions()
                
                if recommendations:
                    logger.info(f"Learning cycle generated {len(recommendations)} recommendations")
                    
                    # Auto-apply high-confidence recommendations
                    for rec in recommendations:
                        if rec.confidence > 0.85 and rec.severity != 'CRIT':
                            human_alignment_ai.apply_adaptation(rec, 'adaptive_system')
                            
            except Exception as e:
                logger.error(f"Learning cycle failed: {e}")
    
    def get_adaptive_statistics(self) -> Dict[str, Any]:
        """Get adaptive alerting statistics"""
        return {
            'stats': self.stats.copy(),
            'config': {
                'enable_adaptive_thresholds': self.config.enable_adaptive_thresholds,
                'enable_relevance_filtering': self.config.enable_relevance_filtering,
                'min_relevance_threshold': self.config.min_relevance_threshold
            },
            'cache_size': len(self.adaptation_cache),
            'learning_metrics': human_alignment_ai.get_learning_metrics().__dict__
        }
    
    def get_adaptation_summary(self) -> List[Dict[str, Any]]:
        """Get summary of applied adaptations"""
        try:
            con = connect()
            rows = con.execute("""
                SELECT rule_id, severity, symbol, horizon_s, action, 
                       current_value, recommended_value, confidence, applied_ms
                FROM alert_adaptations 
                WHERE status = 'applied'
                ORDER BY applied_ms DESC
                LIMIT 20
            """).fetchall()
            
            summary = []
            for row in rows:
                summary.append({
                    'rule_id': row[0],
                    'severity': row[1],
                    'symbol': row[2],
                    'horizon_s': row[3],
                    'action': row[4],
                    'current_value': row[5],
                    'recommended_value': row[6],
                    'confidence': row[7],
                    'applied_ms': row[8]
                })
            
            return summary
        except Exception as e:
            logger.error(f"Failed to get adaptation summary: {e}")
            return []
        finally:
            try:
                con.close()
            except:
                pass
    
    def force_learning_cycle(self) -> List[Dict[str, Any]]:
        """Force a learning cycle"""
        recommendations = human_alignment_ai.learn_from_interactions()
        
        result = {
            'timestamp': time.time(),
            'recommendations_count': len(recommendations),
            'recommendations': [
                {
                    'rule_id': rec.rule_id,
                    'action': rec.action.value,
                    'confidence': rec.confidence,
                    'reasoning': rec.reasoning
                }
                for rec in recommendations
            ]
        }
        
        return result
    
    def reset_adaptations(self, rule_id: Optional[str] = None):
        """Reset adaptations (for testing or emergency)"""
        try:
            con = connect()
            if rule_id:
                con.execute("UPDATE alert_adaptations SET status = 'reset' WHERE rule_id = ?", (rule_id,))
            else:
                con.execute("UPDATE alert_adaptations SET status = 'reset'")
            
            con.commit()
            
            # Clear cache
            self.adaptation_cache.clear()
            
            logger.warning(f"Reset adaptations for rule: {rule_id or 'ALL'}")
            
        except Exception as e:
            logger.error(f"Failed to reset adaptations: {e}")
        finally:
            try:
                con.close()
            except:
                pass

# Global adaptive alerting instance
adaptive_alerting = AdaptiveAlerting()
